# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cf559673cab7f937d9a828dd78a73d91"
name = "i-correct-delivery-app"
handle = "i-correct-delivery-app"
application_url = "https://assurance-expanded-awesome-mu.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "hydrogen-devstore.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_assigned_fulfillment_orders,read_customers,read_fulfillments,read_inventory,read_locations,read_orders,read_products,read_themes,write_assigned_fulfillment_orders,write_customers,write_fulfillments,write_inventory,write_locations,write_orders,write_products,write_themes"

[auth]
redirect_urls = [
  "https://assurance-expanded-awesome-mu.trycloudflare.com/auth/callback",
  "https://assurance-expanded-awesome-mu.trycloudflare.com/auth/shopify/callback",
  "https://assurance-expanded-awesome-mu.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[app_proxy]
url = "https://assurance-expanded-awesome-mu.trycloudflare.com"
subpath = "proxy"
prefix = "apps"

[pos]
embedded = false
