# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e19e19721d52e7e139f079930085f9ed"
application_url = "https://wishlist-pro-x.fly.dev"
embedded = true
name = "Wishlist ProX"
handle = "wishlist-prox"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request" ]
  uri = "/webhooks/app/compliance"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/redact" ]
  uri = "/webhooks/app/compliance"

  [[webhooks.subscriptions]]
  compliance_topics = [ "shop/redact" ]
  uri = "/webhooks/app/compliance"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_customers,read_customers,write_themes,read_online_store_navigation,write_online_store_navigation,read_themes,write_products,read_products,write_orders,read_orders,write_pixels,read_online_store_pages,read_inventory,read_locations"

[auth]
redirect_urls = [
  "https://wishlist-pro-x.fly.dev/auth/callback",
  "https://wishlist-pro-x.fly.dev/auth/shopify/callback",
  "https://wishlist-pro-x.fly.dev/api/auth/callback"
]

[app_proxy]
url = "https://wishlist-pro-x.fly.dev/app/wishlistProX"
subpath = "wishlist-prox-app-proxy"
prefix = "apps"

[pos]
embedded = false

[build]
dev_store_url = "app-wishlist-store.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
